### ISSUE TITLE
incident vs. cumulative calculation of cCFR

### ISSUE THREAD

**Issue by nickblink** [thimotei/CFR_calculation#10]
Hi, I am confused about the calculation of the cCFR. Using the code below, it calculates cCFR with daily incidence but cumulative under-reporting. So for example, if on day d 100 people died in a country and 1000 of the reported cases are expected to have resolved by now (even though there could be something like 2000 reported cases), then the cCFR would be calculated as 100/1000 = 10%. However, shouldn't the cCFR be the cumulative sum of deaths until d divided by the number of resolved cases until d?

If you wanted to calculate daily cCFR, then perhaps it would make sense to divide by the number of cases that would be expected to be resolved exactly on day d, though intuitively this makes less sense than using cumulative counts.

If I am misunderstanding the code or calculation of cCFR, please let me know. Thanks for your work!

  p_tt <- (death_incidence/cumulative_known_t) %>% pmin(.,1)

**Comment by goldingn** [comment]
I think you're referring to this line in the temporal forecasts we're working on: https://github.com/thimotei/CFR_calculation/blob/d9ec8a88d0095409d298b87d8756129ff431e76f/global_estimates/scripts/plot_temporal/scale_cfr_temporal.R#L22

You're absolutely right that using the daily incidence by the cumulative cases doesn't make sense. In this case, it's just that the object `cumulative_known_t` is mislabelled - it's not actually the cumulative number cases with known outcomes, but the daily number. You can see from this line of code that values are appended, rather than added, to this value: https://github.com/thimotei/CFR_calculation/blob/d9ec8a88d0095409d298b87d8756129ff431e76f/global_estimates/scripts/plot_temporal/scale_cfr_temporal.R#L16

It's misnamed because we switched from using total numbers (total deaths over total cases with known outcomes to date) for the point estimates, to daily numbers for the temporal models. We're still refining those models, so haven't gotten around to tidying up the code yet!

**Comment by nickblink** [comment]
That makes sense. About the incident calculation of CFR, have you experimented with smoothing the death counts, such as taking an three-day window average of deaths? I am not sure if this methodologically makes sense, but it would make the estimates of CFR and under-reporting vary less across days.

**Comment by goldingn** [comment]
We're doing that in a model-based way. Smoothing the reporting rate estimate, so that the deaths on one day influence (due to temporal correlation) the estimates on days before and after. The degree of temporal correlation (how many days to smooth over) is then also estimated from the data.

**Comment by nickblink** [comment]
Nice.

Also, this is an issue with the original paper. The reported s.d. given the median and mean should really be
